name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ai-bim-assistant-poc
  FUNCTION_NAME: zoidberg-bim-assistant
  RUNTIME: nodejs20
  ENTRY_POINT: zoidbergAssistant

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: false

      - name: Deploy to Google Cloud Functions
        run: |
          gcloud functions deploy ${{ env.FUNCTION_NAME }} \
            --runtime ${{ env.RUNTIME }} \
            --trigger-http \
            --entry-point ${{ env.ENTRY_POINT }} \
            --source .
